# Generated by Django 5.0.4 on 2024-04-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BookListAPI", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="book",
            new_name="BookListAPI_price_idx",
            old_name="BookListAPI_price_779a55_idx",
        ),
        migrations.AddField(
            model_name="book",
            name="inventory",
            field=models.IntegerField(default=0),
        ),
    ]
